[project]
name = "todooit"
version = "1.0.0"
description = "A beautiful, versatile todo app in your terminal for a keyboard based workflow."
requires-python = ">=3.9"
authors = [
    {name = "Georg Slamanig", email = "georgslamanig@gmail.com"}
]
license = "MIT"
readme = "README.md"
dependencies = [
    "click>=8.1.8",
    "platformdirs>=4.4.0",
    "pyperclip>=1.10.0",
    "python-dateutil>=2.9.0.post0",
    "sqlalchemy>=2.0.43",
    "textual>=6.1.0",
    "typing-extensions>=4.5.0",
]

[project.urls]
Homepage = "https://github.com/gslama12/todooit"
Repository = "https://github.com/gslama12/todooit"

[project.scripts]
todooit = "todooit.__main__:main"

[dependency-groups]
dev = [
    "coverage>=7.10.7",
    "faker>=37.8.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "ruff>=0.13.1",
    "textual-dev>=1.7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["todooit"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
asyncio_default_fixture_loop_scope = "function"

[tool.ruff.lint]
ignore = ["E712"]

[tool.coverage.report]
omit = ["todooit/utils/default_config.py"]
